image: continuumio/miniconda3:latest

before_script:
  - apt-get update
  - wget -O Mambaforge.sh  "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
  - bash Mambaforge.sh -b -p "${HOME}/conda"
  - source "${HOME}/conda/etc/profile.d/mamba.sh"
  - conda activate

build:
  script:
    - mamba env create --quiet --name refit_fvs --file environment.yml
    - source activate refit_fvs
    - cd refit_fvs && pip install -e . && cd ..
  allow_failure: false

lint:
  before_script:
  - mamba install flake8
  script:
    - flake8 . --max-line-length=88 --ignore=F841,W503
  allow_failure: false
