image: continuumio/miniconda3:latest

build:
  script:
    - conda env create --quiet --name refit_fvs --file environment.yml
    - source activate refit_fvs
    - conda install -c conda-forge coveralls flake8 black
    - cd refit_fvs && pip install -e . && cd ..
  allow_failture: false

lint:
  script:
    - flake8 . --max-line-length=88 --ignore=F841,W503
  allow_failure: false
