image: condaforge/mambaforge:latest

build:
  script:
    - mamba env create --quiet --name refit_fvs --file environment.yml
    - source activate refit_fvs
    - pip install -e .
  allow_failure: false

lint:
  before_script:
  - mamba install flake8
  script:
    - flake8 . --max-line-length=88 --ignore=F841,W503
  allow_failure: false
